# MABe Mouse Behavior Detection - H100 Optimized Configuration
# Ultra-fast training with motion features

# Data settings
data_dir: '/vol/data/kaggle'
use_kaggle_data: true

# Mouse parameters
num_mice: 4
num_keypoints: 18

# Model settings
model_type: 'conv_bilstm'
input_dim: 288  # 144 (coords) + 72 (speed) + 72 (accel)
num_classes: 4  # 0: background, 1: social, 2: mating, 3: aggressive

# Conv1DBiLSTM settings
conv_channels: [64, 128, 256]
lstm_hidden: 256
lstm_layers: 2

# Sequence settings
sequence_length: 100
frame_gap: 1
fps: 33.3

# Training settings - H100 Optimized
epochs: 100
batch_size: 384  # Large batch for H100 (80GB VRAM)
learning_rate: 0.0004  # Slightly higher for large batch
weight_decay: 0.0001
optimizer: 'adamw'
grad_clip: 1.0

# Warmup for large batch
warmup_epochs: 3

# Loss settings
loss: 'cross_entropy'
class_weights: [1.0, 5.0, 8.0, 8.0]  # Balanced weights
label_smoothing: 0.0

# Learning rate scheduler
scheduler: 'plateau'
scheduler_patience: 5
scheduler_factor: 0.5
min_lr: 0.00001

# Data augmentation
use_augmentation: true
noise_std: 0.01
temporal_jitter: 2

# Regularization
dropout: 0.3
mixup_alpha: 0.0

# Data loader settings - H100 optimized
num_workers: 2  # Modal limitation

# Checkpoint settings
checkpoint_dir: '/vol/checkpoints/h100'
save_freq: 5
early_stopping_patience: 15

# Device
device: 'cuda'

# Random seed
seed: 42

# Evaluation
eval_metrics: ['accuracy', 'f1_macro', 'precision', 'recall']

# Motion features
use_motion_features: true
motion_fps: 33.3
