# V7 Interval Detection - RTX 5090 Local Training

# Data settings
data_dir: '/Users/aaronpang/PycharmProjects/mabe_mouse_behavior/data/kaggle'
sequence_length: 1000  # Full video sequences

# Model architecture
input_dim: 142  # 71 keypoints × 2
hidden_dim: 256
num_actions: 4  # attack, avoid, chase, chaseattack
num_agents: 4

# Anchor settings (multi-scale interval detection)
anchor_scales: [10, 30, 60, 120, 240]  # Frame lengths

# Training settings - RTX 5090 Optimized
epochs: 100
batch_size: 16  # 5090 has 32GB VRAM
learning_rate: 0.0001
weight_decay: 0.00001
optimizer: 'adamw'
grad_clip: 1.0

# Loss settings
iou_threshold_pos: 0.5  # Positive anchor threshold
iou_threshold_neg: 0.4  # Negative anchor threshold
focal_alpha: 0.25
focal_gamma: 2.0

# Inference settings
score_threshold: 0.5  # Objectness score threshold
nms_threshold: 0.3    # NMS IoU threshold

# Data loader
num_workers: 8
pin_memory: true

# Checkpoint settings
checkpoint_dir: 'checkpoints/v7_5090'
save_freq: 5
early_stopping_patience: 15

# Device
device: 'cuda'
gpu_id: 0

# Random seed
seed: 42

# Evaluation
iou_eval_threshold: 0.5  # IoU threshold for F1 metric
eval_metrics: ['precision', 'recall', 'f1']
